apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asx-ingress
  labels:
    app: asx
    {{- toYaml .Values.labels | nindent 4 }}
  annotations:
{{ if eq .Values.spec.ingress.type "nginx" }}
    #nginx annotations
{{ else }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: 'ip'
  {{ if .Values.spec.ingress.host }} # we can't use grouping without custom domain
    alb.ingress.kubernetes.io/group.name: burnham
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
  {{ else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  {{ end }}
    alb.ingress.kubernetes.io/backend-protocol: 'HTTP'
    alb.ingress.kubernetes.io/tags: Environment={{ .Values.labels.env }},Team=Burnham
{{ end }}
  {{ if .Values.spec.ingress.host }}
    external-dns.alpha.kubernetes.io/set-identifier: {{ .Values.spec.clusterName }}
    external-dns.alpha.kubernetes.io/aws-weight: '{{ .Values.spec.ingress.route53_weight }}'
    external-dns.alpha.kubernetes.io/ttl: "10"
  {{ end }}    
spec:
{{ if eq .Values.spec.ingress.type "nginx" }}
  kubernetes.io/ingress.class: "nginx"
{{ else }}
  ingressClassName: alb
{{ end }}
  rules:
{{ if .Values.spec.ingress.host }}
  - host: asx.{{ .Values.spec.ingress.host }}
{{ else }}
  - host:
{{ end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: asx
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: asx
  labels:
    app: asx-ingress-{{ .Values.spec.env }}  
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: burnham
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asx
  labels:
    app: asx
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: asx
  template:
    metadata:
      labels:
        app: asx
        seb: test
    spec:
      containers:
        - name: asx
          image: 045549827180.dkr.ecr.us-west-2.amazonaws.com/asxmod_group1:v1
          imagePullPolicy: Always
          env:
          - name: CLUSTER_NAME
            value: {{ .Values.spec.clusterName }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 50Mi
      {{ if .Values.spec.karpenterInstanceProfile }}
      nodeSelector:
        team: asx
        type: karpenter
      tolerations:
        - key: 'asx'
          operator: 'Exists'
          effect: 'NoSchedule'
      {{ end }}
