apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-asxapp
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  destination:
    namespace: team-asxapp
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: teams/team-asxapp/dev
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true